# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/africk/proj/screaming_insects_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/africk/proj/screaming_insects_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/africk/proj/screaming_insects_cpp/CMakeFiles /home/africk/proj/screaming_insects_cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/africk/proj/screaming_insects_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SDL2Test

# Build rule for target.
SDL2Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2Test
.PHONY : SDL2Test

# fast build rule for target.
SDL2Test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/build
.PHONY : SDL2Test/fast

src/Vector2.o: src/Vector2.cpp.o
.PHONY : src/Vector2.o

# target to build an object file
src/Vector2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Vector2.cpp.o
.PHONY : src/Vector2.cpp.o

src/Vector2.i: src/Vector2.cpp.i
.PHONY : src/Vector2.i

# target to preprocess a source file
src/Vector2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Vector2.cpp.i
.PHONY : src/Vector2.cpp.i

src/Vector2.s: src/Vector2.cpp.s
.PHONY : src/Vector2.s

# target to generate assembly for a file
src/Vector2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/Vector2.cpp.s
.PHONY : src/Vector2.cpp.s

src/classes.o: src/classes.cpp.o
.PHONY : src/classes.o

# target to build an object file
src/classes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/classes.cpp.o
.PHONY : src/classes.cpp.o

src/classes.i: src/classes.cpp.i
.PHONY : src/classes.i

# target to preprocess a source file
src/classes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/classes.cpp.i
.PHONY : src/classes.cpp.i

src/classes.s: src/classes.cpp.s
.PHONY : src/classes.s

# target to generate assembly for a file
src/classes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/classes.cpp.s
.PHONY : src/classes.cpp.s

src/funcs.o: src/funcs.cpp.o
.PHONY : src/funcs.o

# target to build an object file
src/funcs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/funcs.cpp.o
.PHONY : src/funcs.cpp.o

src/funcs.i: src/funcs.cpp.i
.PHONY : src/funcs.i

# target to preprocess a source file
src/funcs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/funcs.cpp.i
.PHONY : src/funcs.cpp.i

src/funcs.s: src/funcs.cpp.s
.PHONY : src/funcs.s

# target to generate assembly for a file
src/funcs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/funcs.cpp.s
.PHONY : src/funcs.cpp.s

src/group.o: src/group.cpp.o
.PHONY : src/group.o

# target to build an object file
src/group.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/group.cpp.o
.PHONY : src/group.cpp.o

src/group.i: src/group.cpp.i
.PHONY : src/group.i

# target to preprocess a source file
src/group.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/group.cpp.i
.PHONY : src/group.cpp.i

src/group.s: src/group.cpp.s
.PHONY : src/group.s

# target to generate assembly for a file
src/group.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/group.cpp.s
.PHONY : src/group.cpp.s

src/insect.o: src/insect.cpp.o
.PHONY : src/insect.o

# target to build an object file
src/insect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/insect.cpp.o
.PHONY : src/insect.cpp.o

src/insect.i: src/insect.cpp.i
.PHONY : src/insect.i

# target to preprocess a source file
src/insect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/insect.cpp.i
.PHONY : src/insect.cpp.i

src/insect.s: src/insect.cpp.s
.PHONY : src/insect.s

# target to generate assembly for a file
src/insect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/insect.cpp.s
.PHONY : src/insect.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/random.o: src/random.cpp.o
.PHONY : src/random.o

# target to build an object file
src/random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/random.cpp.o
.PHONY : src/random.cpp.o

src/random.i: src/random.cpp.i
.PHONY : src/random.i

# target to preprocess a source file
src/random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/random.cpp.i
.PHONY : src/random.cpp.i

src/random.s: src/random.cpp.s
.PHONY : src/random.s

# target to generate assembly for a file
src/random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/random.cpp.s
.PHONY : src/random.cpp.s

src/sprite.o: src/sprite.cpp.o
.PHONY : src/sprite.o

# target to build an object file
src/sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/sprite.cpp.o
.PHONY : src/sprite.cpp.o

src/sprite.i: src/sprite.cpp.i
.PHONY : src/sprite.i

# target to preprocess a source file
src/sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/sprite.cpp.i
.PHONY : src/sprite.cpp.i

src/sprite.s: src/sprite.cpp.s
.PHONY : src/sprite.s

# target to generate assembly for a file
src/sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/sprite.cpp.s
.PHONY : src/sprite.cpp.s

src/texture.o: src/texture.cpp.o
.PHONY : src/texture.o

# target to build an object file
src/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/texture.cpp.o
.PHONY : src/texture.cpp.o

src/texture.i: src/texture.cpp.i
.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s
.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

src/vals.o: src/vals.cpp.o
.PHONY : src/vals.o

# target to build an object file
src/vals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/vals.cpp.o
.PHONY : src/vals.cpp.o

src/vals.i: src/vals.cpp.i
.PHONY : src/vals.i

# target to preprocess a source file
src/vals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/vals.cpp.i
.PHONY : src/vals.cpp.i

src/vals.s: src/vals.cpp.s
.PHONY : src/vals.s

# target to generate assembly for a file
src/vals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SDL2Test.dir/build.make CMakeFiles/SDL2Test.dir/src/vals.cpp.s
.PHONY : src/vals.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SDL2Test"
	@echo "... src/Vector2.o"
	@echo "... src/Vector2.i"
	@echo "... src/Vector2.s"
	@echo "... src/classes.o"
	@echo "... src/classes.i"
	@echo "... src/classes.s"
	@echo "... src/funcs.o"
	@echo "... src/funcs.i"
	@echo "... src/funcs.s"
	@echo "... src/group.o"
	@echo "... src/group.i"
	@echo "... src/group.s"
	@echo "... src/insect.o"
	@echo "... src/insect.i"
	@echo "... src/insect.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/sprite.o"
	@echo "... src/sprite.i"
	@echo "... src/sprite.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
	@echo "... src/vals.o"
	@echo "... src/vals.i"
	@echo "... src/vals.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

